# -*- coding: utf-8 -*-
"""Artificial_Neural_Network_ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLI5HbtwEo2KXvNOhWxgUEm5vLTN9Qvz
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense,Input
from keras.optimizers import SGD
from keras.losses import BinaryCrossentropy

# Hyperparameters
from keras.initializers import HeNormal
from keras.layers import BatchNormalization, Dropout

from keras.callbacks import EarlyStopping, ModelCheckpoint

# Load the breast cancer dataset
data = load_breast_cancer()

# Display the features (data) from the dataset
data["data"]

# Display the target (labels) from the dataset
data['target']

# Display the shape of the target array
data['target'].shape

# Display the shape of the data array
data['data'].shape

# to_categorical is used to convert class labels into one-hot encoded vectors, which many neural networks in Keras require when performing multi-class classification. Also the loss function expects one-hot encoded labels.
# Prediction: [0.1, 0.2, 0.7] Actual: [0, 0, 1]
#The loss function calculates the difference between these vectors.

# Convert the target labels to one-hot encoded format
y_cat = to_categorical(data['target'])

# Display the one-hot encoded target labels
y_cat

# Split the data into training and testing sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(data['data'], y_cat, test_size = 0.2)

# Display the shapes of the training and testing data and labels
x_train.shape, x_test.shape, y_train.shape, y_test.shape

# Sequential means the neural network layers are stacked one after another in order.
# Input → Hidden Layer 1 → Hidden Layer 2 → Output Layer It is called sequential because data flows sequentially through the layers.
# Building the architecture for Neural Network

# Initialize a sequential model
model = Sequential()

# 3 ways to inform the input layer X-features
#  model.add(Input(shape=(8,)))
#  model.add(Input(shape=(df.shape[1]-1,))) # from df before the X & Y split
#  model.add(Input(shape=(X.shape[1],))) # after X and Y

# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

#If input layer is not explicitly defined then you have to provide input shape in first hidden layer
#model.add(Dense(10,input_shape = (x_train.shape[1],),activation='sigmoid'))

# Add the first hidden layer with 32 units and sigmoid activation
model.add(Dense(32,activation = 'sigmoid',name='Hidden_Layer_1'))

# Add the second hidden layer with 16 units and sigmoid activation
model.add(Dense(16,activation = 'sigmoid', name="Hidden_Layer_2"))

# Add the output layer with a number of units equal to the number of output classes and softmax activation
model.add(Dense(y_train.shape[1],activation = 'softmax', name="Output_Layer"))

# Install the keras_visualizer library
!pip install keras_visualizer

# Import the keras_visualizer library
import keras_visualizer

# Visualize the Keras model and save it as a PNG file
keras_visualizer.visualizer(model,file_name='Modelpic',file_format='png')

# Import necessary modules for displaying images in IPython
from IPython.display import Image, display

# Display the saved model visualization image
display(Image('Modelpic.png'))

# Initialize the Stochastic Gradient Descent (SGD) optimizer
sgd_optimizer = SGD()

# Initialize the Binary Crossentropy loss function
binary_loss = BinaryCrossentropy()

# Compile the model with the specified optimizer, loss function, and metrics
model.compile(optimizer = sgd_optimizer, loss = binary_loss, metrics = ['accuracy'])

# Display a summary of the model's architecture, including layer names, output shapes, and number of parameters
model.summary()

# Train the model using the training data, for a specified number of epochs, batch size, and validation data
history = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

import matplotlib.pyplot as plt

def plot_history(history):
  # Plot the training loss over epochs
  plt.plot(history.history['loss'], label='train Loss')
  # Plot the validation loss over epochs
  plt.plot(history.history['val_loss'], label='val Loss')

  # Set the x-axis label
  plt.xlabel('epoch')
  # Set the y-axis label
  plt.ylabel('loss')

plot_history(history)

# Initialize the Binary Crossentropy loss function
binary_loss = BinaryCrossentropy()

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss = binary_loss, metrics = ['accuracy'])

# Train the model with the updated Adam optimizer, for a specified number of epochs, batch size, and validation data
history1 = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

plot_history(history1)

# Non Saturating Activation Function

# Initialize a new sequential model
model = Sequential()

# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

# Add the first hidden layer with 32 units and ReLU activation
model.add(Dense(32,activation = 'relu',name='Hidden_Layer_1'))

# Add the second hidden layer with 16 units and ReLU activation
model.add(Dense(16,activation = 'relu', name="Hidden_Layer_2"))

# Add the output layer with a number of units equal to the number of output classes and sigmoid activation
model.add(Dense(y_train.shape[1],activation = 'sigmoid', name="Output_Layer"))

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

# Train the model with the updated architecture, for a specified number of epochs, batch size, and validation data
history2 = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

plot_history(history2)

# Install the scikeras library
!pip install scikeras

# Proper Initialization of Weights
# Initialize the HeNormal initializer for kernel weights
initializer = HeNormal()

model = Sequential()

# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

# Add the first hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(32,kernel_initializer = initializer, activation = 'relu',name='Hidden_Layer_1'))

# Add the second hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(16,kernel_initializer = initializer,activation = 'relu', name="Hidden_Layer_2"))

# Add the output layer with HeNormal kernel initializer, sigmoid activation
model.add(Dense(y_train.shape[1],kernel_initializer = initializer, activation = 'sigmoid', name="Output_Layer"))

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

# Train the model with the updated architecture, for a specified number of epochs, batch size, and validation data
history3 = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

plot_history(history3)

# Batch Normalization

# Initialize a sequential model
model = Sequential()

# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

# Add the first hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(32,kernel_initializer = initializer, activation = 'relu',name='Hidden_Layer_1'))
# Add Batch Normalization layer after the first hidden layer
model.add(BatchNormalization())

# Add the second hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(16,kernel_initializer = initializer,activation = 'relu', name="Hidden_Layer_2"))
# Add Batch Normalization layer after the second hidden layer
model.add(BatchNormalization())

# Add the output layer with HeNormal kernel initializer, sigmoid activation
model.add(Dense(y_train.shape[1],kernel_initializer = initializer, activation = 'sigmoid', name="Output_Layer"))

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

# Train the model with the updated architecture, for a specified number of epochs, batch size, and validation data
history4 = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

plot_history(history4)

# Display a summary of the model's architecture, including layer names, output shapes, and number of parameters
model.summary()

# Dropout

# Initialize a sequential model
model = Sequential()

# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

# Add the first hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(32,kernel_initializer = initializer, activation = 'relu',name='Hidden_Layer_1'))
# Add Batch Normalization layer after the first hidden layer
model.add(BatchNormalization())
# Add a Dropout layer with a dropout rate of 0.5 (50% of neurons will be randomly set to 0 during training)
model.add(Dropout(0.5))

# Add the second hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(16,kernel_initializer = initializer,activation = 'relu', name="Hidden_Layer_2"))
# Add Batch Normalization layer after the second hidden layer
model.add(BatchNormalization())
# Add a Dropout layer with a dropout rate of 0.5 (50% of neurons will be randomly set to 0 during training)
model.add(Dropout(0.5))

# Add the output layer with HeNormal kernel initializer, sigmoid activation
model.add(Dense(y_train.shape[1],kernel_initializer = initializer, activation = 'sigmoid', name="Output_Layer"))

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

# Train the model with the updated architecture, for a specified number of epochs, batch size, and validation data
history5 = model.fit(x_train, y_train, epochs=100, batch_size=100, validation_data=(x_test, y_test) ,verbose=1)

plot_history(history5)

# Display a summary of the model's architecture, including layer names, output shapes, and number of parameters
model.summary()

# Visualize the Keras model and save it as a PNG file
keras_visualizer.visualizer(model,file_name='Modelpic1',file_format='png')

# Display the saved model visualization image
display(Image('Modelpic1.png'))

#If my model doesn’t improve meaningfully for 5 rounds, stop training.
# Patience - How many epochs to wait before stopping?  If no improvement happens for 5 consecutive epochs, training stops
# Minimum improvement required to count as progress. Model must improve at least by 0.001 (0.1%)

# Define an EarlyStopping callback to monitor validation accuracy and stop training if it doesn't improve
callback = EarlyStopping(monitor='val_accuracy', min_delta = 0.001 , patience=5)

# Initialize a sequential model
model = Sequential()
# Add the input layer, specifying the shape of the input features
model.add(Input(shape = (x_train.shape[1],)))

# Add the first hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(32,kernel_initializer = initializer, activation = 'relu',name='Hidden_Layer_1'))
# Add Batch Normalization layer after the first hidden layer
model.add(BatchNormalization())
# Add a Dropout layer with a dropout rate of 0.5
model.add(Dropout(0.5))

# Add the second hidden layer with HeNormal kernel initializer, ReLU activation
model.add(Dense(16,kernel_initializer = initializer,activation = 'relu', name="Hidden_Layer_2"))
# Add Batch Normalization layer after the second hidden layer
model.add(BatchNormalization())
# Add a Dropout layer with a dropout rate of 0.5
model.add(Dropout(0.5))

# Add the output layer with HeNormal kernel initializer, sigmoid activation
model.add(Dense(y_train.shape[1],kernel_initializer = initializer, activation = 'sigmoid', name="Output_Layer"))

# Compile the model with the Adam optimizer, binary crossentropy loss, and accuracy metric
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

# Train the model with the updated architecture, early stopping callback, for a specified number of epochs, batch size, and validation data
history6 = model.fit(x_train, y_train, epochs=200, batch_size=100, validation_data=(x_test, y_test) ,verbose=1, callbacks=[callback])

# Initialize He Normal (best for ReLU activation)
initializer = HeNormal()

# Create Sequential model (layer-by-layer stack)
model = Sequential()

# Input layer: defines number of input features
model.add(Input(shape=(x_train.shape[1],)))

# Hidden Layer 1
model.add(Dense(
    32,                            # Number of neurons
    activation='relu',             #ReLU activation (avoids vanishing gradient)
    kernel_initializer=initializer # He initialization for better weight scaling
))

# Batch Normalization: stabilizes learning
model.add(BatchNormalization())

# Dropout: randomly drop 50% neurons to prevent overfitting
model.add(Dropout(0.5))

# Hidden Layer 2
model.add(Dense(
    16,                              # Fewer neurons for dimensional reduction
    activation='relu',
    kernel_initializer=initializer
))

# Batch Normalization again
model.add(BatchNormalization())

# Dropout: smaller dropout (20%) for fine regularization
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(
    y_train.shape[1],                # Output neurons = number of classes (2)
    activation='sigmoid'             # Sigmoid for binary classification
))

# Compile model
model.compile(
    optimizer='adam',                # Adaptive optimizer (fast + efficient)
    loss='binary_crossentropy',      # Suitable for binary classification
    metrics=['accuracy']             # Track accuracy
)

# Early Stopping callback
callback = EarlyStopping(
    monitor='val_accuracy',          # Monitor validation accuracy
    min_delta=0.001,                 # Minimum improvement required
    patience=20,                     # Wait 5 epochs before stopping
    restore_best_weights=True        # Restore best weights after stopping
)

# Train the model
history7 = model.fit(
    x_train, y_train,
    epochs=200,
    batch_size=100,
    validation_data=(x_test, y_test),
    callbacks=[callback]
)

plot_history(history7)